# Kubernetes Service Accounts with Workload Identity
# These link K8s service accounts to GCP service accounts
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  namespace: hta-prod
  annotations:
    iam.gke.io/gcp-service-account: production-api@hta-platform-prod.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker
  namespace: hta-prod
  annotations:
    iam.gke.io/gcp-service-account: production-worker@hta-platform-prod.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-hta
  namespace: hta-prod
  annotations:
    iam.gke.io/gcp-service-account: production-web@hta-platform-prod.iam.gserviceaccount.com
