/**
 * Every parameter the master registry records.
 *
 * Forty-seven of them, which is too many for a plain select and why the
 * capability form searches rather than scrolls. This is the vocabulary the
 * registry already uses; typing something not on the list is still allowed,
 * because a lab that starts calibrating something new should not have to wait
 * for a deploy.
 */
export const CALIBRATION_PARAMETERS = [
  'AC Current',
  'AC Voltage',
  'Acceleration',
  'Air Flow',
  'Air Velocity',
  'Angle',
  'CO2',
  'Capacitance',
  'Compressed Air Flow',
  'Conductivity',
  'DC Current',
  'DC Voltage',
  'Dew Point Temperature',
  'Differential Pressure',
  'Displacement',
  'Flatness',
  'Flow',
  'Force (Compression)',
  'Force (Tension)',
  'Frequency',
  'Gauge Pressure',
  'Hardness',
  'Length',
  'Level / Inclination',
  'Light Intensity',
  'Liquid Flow',
  'Mass',
  'Moisture Content',
  'Parallelness',
  'Particle Count',
  'Pressure',
  'RTD',
  'Relative Humidity',
  'Resistance',
  'Sound Pressure Level',
  'Speed',
  'Speed (Contact)',
  'Speed (Non-Contact)',
  'Temperature',
  'Thermocouple',
  'Thickness',
  'Three-phase AC Power',
  'Time',
  'Time Interval',
  'Ultra Vacuum',
  'Vacuum',
  'Velocity',
] as const
