// Master Instrument Registry - schema 2.0
//
// Types for src/data/master-instrument-registry.json, generated by
// scripts/standardize_registry.py from the working registry under reference_docs/.
//
// This replaces the flat MasterInstrument shape in master-instruments.ts, where an
// instrument carried `parameter_group` plus a list of capability slugs and a flat
// `range[]`. The hierarchy is now:
//
//   asset (an asset number in the lab's master list)
//     └── unit (a physical instrument with its own certificate and due date)
//           └── capability profile (a parameter it can source or measure)
//                 └── bucket (a sub-range with its own least count and accuracy)
//
// Most assets hold exactly one unit. Several hold more - a calibrator and its current
// coil, three paperless recorders - which the lab distinguishes with lettered
// certificates (188A, 188B, 188C).
//
// Do not edit the JSON by hand - regenerate it.

export type ProfileRole = 'source' | 'measuring'

export type SubtypeKind =
  /** Type B/E/J/K/L/N/R/S/T/U */
  | 'thermocouple_type'
  /** Pt-100 / Pt-200 / Pt-46 / Cu-53 / Ni-100 / Ni-120 */
  | 'rtd_curve'
  /** Physical size of a gauge artifact (e.g. "24.12mm") - NOT an element type */
  | 'gauge_dimension'

/**
 * What a percentage accuracy is a percentage *of*.
 *
 * `null` means the certificate stated a percentage without saying of what. That is not
 * the same as "assume reading": for a CO2 transmitter, "±1%" could mean 1% of reading,
 * 1% of full scale, or 1 percentage point of concentration - a 250x spread at the low
 * end. Treat null as unresolved and exclude the bucket from accuracy comparisons.
 */
export type PercentBasis = 'reading' | 'full_scale' | 'span' | null

/** Accuracy stated as a fixed ± value in a unit, e.g. "±0.23 °C". */
export interface SymmetricAccuracy {
  type: 'symmetric'
  value: number
  unit: string
  polarity: string
}

/**
 * Accuracy stated as a formula, e.g. "±0.02% of reading ±2 count".
 *
 * Has no single scalar value: it only resolves against a specific reading. Any filter
 * that compares accuracy must call an evaluator rather than reading a `value` field.
 */
export interface FormulaAccuracy {
  type: 'formula'
  expression: string
  percent_of: PercentBasis
  percent_value: number | null
  digits: number | null
  digits_unit: string | null
  polarity: string
}

/** Accuracy stated only as a class, e.g. "F2 Class". Carries no number at all. */
export interface ClassAccuracy {
  type: 'class'
  class: string
  polarity: string | null
}

export type Accuracy = SymmetricAccuracy | FormulaAccuracy | ClassAccuracy

export interface LeastCount {
  value: number
  unit: string
}

/** A sub-range of a capability profile with its own least count and accuracy. */
export interface CapabilityBucket {
  id: string
  min: number | null
  max: number | null
  min_inclusive: boolean
  max_inclusive: boolean
  /** null when the certificate states no resolution. */
  least_count: LeastCount | null
  /** null when the certificate states no accuracy (uncertainty only, or nothing). */
  accuracy: Accuracy | null
}

/**
 * A reference artifact realises discrete nominal values, not a continuous range.
 *
 * A slip gauge set can supply only its nominal sizes (or stacked combinations); a
 * surface plate has a flatness deviation over a fixed surface. Modelling these with
 * min/max would claim they can supply any value in between, which is false.
 */
export interface ArtifactCapability {
  /** Slip gauge sets: one entry per block. */
  blocks?: Array<{
    nominal_mm: number
    deviation_um: number
    var_min_um?: number
    var_max_um?: number
  }>
  /** Pitch-block checkers: the discrete sizes available. */
  blocks_mm?: number[]
  max_abs_error_mm?: number
  /** Surface plates. */
  surface_size_mm?: string
  measured_flatness_um?: number
  grade?: string
  grade_tolerance_um?: number
  standard?: string
  measurement_uncertainty?: string
  material?: string
  count?: number
  deviation_unit?: string
}

export interface CapabilityProfile {
  id: string
  /** Standard parameter name. Raw registry variants are normalized away. */
  parameter: string
  role: ProfileRole
  unit: string
  /** `range` capabilities have min/max and buckets; `artifact` ones have `artifact`. */
  kind: 'range' | 'artifact'
  min: number | null
  max: number | null
  min_inclusive: boolean
  max_inclusive: boolean
  buckets: CapabilityBucket[]
  /** e.g. "Type K", "Pt-100", "24.12mm" - read with subtype_kind, not on its own. */
  subtype?: string
  subtype_kind?: SubtypeKind
  /**
   * Some certificates state an operating range narrower than the declared range
   * (e.g. a lux meter declared 0-199990 lux with an operating range of 60-5000).
   */
  operating_range?: { min: number; max: number; unit: string }
  /** Disambiguates profiles that share a parameter, e.g. "height" vs "outside". */
  mode?: string
  /** Present when kind === 'artifact'. */
  artifact?: ArtifactCapability
}

/**
 * One physical instrument, calibrated and certified in its own right.
 *
 * This is the entity a certificate is issued against and the entity a user actually
 * selects as a master - it has its own serial number, calibration date, due date and
 * capabilities. Several units can live under one asset number.
 */
export interface RegistryUnit {
  /**
   * Distinguishes units within an asset. Uses the lab's own certificate letter where
   * one exists ("A", "B", "C" from 188A/188B/188C); otherwise a 1-based ordinal, which
   * is arbitrary - see the `shared_asset_number_without_lettering` integrity issue.
   * Single-unit assets are always "1".
   */
  id: string
  instrument_desc: string | null
  make: string | null
  model: string | null
  serial_no: string | null
  category: string | null
  usage: string | null
  calibrated_at: string | null
  report_no: string | null
  /** ISO date. */
  next_due_on: string | null
  calibration_status: string | null
  sop_references: string[]
  certificate_file: string | null
  capability_profiles: CapabilityProfile[]
  /**
   * Present and false when this unit is known only from a certificate and has no entry
   * in the lab's master list - so no serial number and no attributable calibration
   * dates. Its due status cannot be tracked; do not present it as current.
   */
  has_master_record?: boolean
}

/**
 * One entry in the lab's master list, identified by its asset number.
 *
 * An asset is a grouping, not an instrument. It always has at least one unit, and most
 * have exactly one. Because `units` is never optional there is a single shape to handle:
 * code that wants instruments reads `assets.flatMap(a => a.units)` and never branches.
 */
export interface RegistryAsset {
  /** Normalized asset number, e.g. "227". Unique across the registry. */
  id: string
  /** As printed, e.g. "227 HTAIPL/L". */
  asset_no: string
  unit_count: number
  /** Always at least one entry. */
  units: RegistryUnit[]
}

export interface MasterInstrumentRegistry {
  schema_version: string
  generated_on: string
  source: {
    registry_schema_version: string | null
    normalization_map_version: string | null
  }
  asset_count: number
  unit_count: number
  profile_count: number
  assets: RegistryAsset[]
}

/** Every instrument in the registry, flattened out of its asset grouping. */
export function allUnits(registry: MasterInstrumentRegistry): RegistryUnit[] {
  return registry.assets.flatMap((asset) => asset.units)
}

// ---------------------------------------------------------------------------------
// Narrowing helpers
// ---------------------------------------------------------------------------------

export function isSymmetric(a: Accuracy | null): a is SymmetricAccuracy {
  return a?.type === 'symmetric'
}

export function isFormula(a: Accuracy | null): a is FormulaAccuracy {
  return a?.type === 'formula'
}

export function isClassAccuracy(a: Accuracy | null): a is ClassAccuracy {
  return a?.type === 'class'
}

/**
 * True when an accuracy can be reduced to a number for a given reading.
 *
 * A class accuracy never can. A formula accuracy cannot when its basis is unresolved.
 * Callers that filter on accuracy should check this rather than assuming a value.
 */
export function isComparable(a: Accuracy | null): boolean {
  if (!a) return false
  if (a.type === 'symmetric') return true
  if (a.type === 'formula') return a.percent_of !== null || a.digits !== null
  return false
}
