// Master Instrument Registry - schema 2.0
//
// Types for src/data/master-instrument-registry.json, generated by
// scripts/standardize_registry.py from the working registry under reference_docs/.
//
// This replaces the flat MasterInstrument shape in master-instruments.ts, where an
// instrument carried `parameter_group` plus a list of capability slugs and a flat
// `range[]`. Capability is now hierarchical: an asset has profiles, a profile has
// range buckets, and each bucket carries its own least count and accuracy.
//
// Do not edit the JSON by hand - regenerate it.

export type ProfileRole = 'source' | 'measuring'

export type SubtypeKind =
  /** Type B/E/J/K/L/N/R/S/T/U */
  | 'thermocouple_type'
  /** Pt-100 / Pt-200 / Pt-46 / Cu-53 / Ni-100 / Ni-120 */
  | 'rtd_curve'
  /** Physical size of a gauge artifact (e.g. "24.12mm") - NOT an element type */
  | 'gauge_dimension'

/**
 * What a percentage accuracy is a percentage *of*.
 *
 * `null` means the certificate stated a percentage without saying of what. That is not
 * the same as "assume reading": for a CO2 transmitter, "±1%" could mean 1% of reading,
 * 1% of full scale, or 1 percentage point of concentration - a 250x spread at the low
 * end. Treat null as unresolved and exclude the bucket from accuracy comparisons.
 */
export type PercentBasis = 'reading' | 'full_scale' | 'span' | null

/** Accuracy stated as a fixed ± value in a unit, e.g. "±0.23 °C". */
export interface SymmetricAccuracy {
  type: 'symmetric'
  value: number
  unit: string
  polarity: string
}

/**
 * Accuracy stated as a formula, e.g. "±0.02% of reading ±2 count".
 *
 * Has no single scalar value: it only resolves against a specific reading. Any filter
 * that compares accuracy must call an evaluator rather than reading a `value` field.
 */
export interface FormulaAccuracy {
  type: 'formula'
  expression: string
  percent_of: PercentBasis
  percent_value: number | null
  digits: number | null
  digits_unit: string | null
  polarity: string
}

/** Accuracy stated only as a class, e.g. "F2 Class". Carries no number at all. */
export interface ClassAccuracy {
  type: 'class'
  class: string
  polarity: string | null
}

export type Accuracy = SymmetricAccuracy | FormulaAccuracy | ClassAccuracy

export interface LeastCount {
  value: number
  unit: string
}

/** A sub-range of a capability profile with its own least count and accuracy. */
export interface CapabilityBucket {
  id: string
  min: number | null
  max: number | null
  min_inclusive: boolean
  max_inclusive: boolean
  /** null when the certificate states no resolution. */
  least_count: LeastCount | null
  /** null when the certificate states no accuracy (uncertainty only, or nothing). */
  accuracy: Accuracy | null
}

/**
 * A reference artifact realises discrete nominal values, not a continuous range.
 *
 * A slip gauge set can supply only its nominal sizes (or stacked combinations); a
 * surface plate has a flatness deviation over a fixed surface. Modelling these with
 * min/max would claim they can supply any value in between, which is false.
 */
export interface ArtifactCapability {
  /** Slip gauge sets: one entry per block. */
  blocks?: Array<{
    nominal_mm: number
    deviation_um: number
    var_min_um?: number
    var_max_um?: number
  }>
  /** Pitch-block checkers: the discrete sizes available. */
  blocks_mm?: number[]
  max_abs_error_mm?: number
  /** Surface plates. */
  surface_size_mm?: string
  measured_flatness_um?: number
  grade?: string
  grade_tolerance_um?: number
  standard?: string
  measurement_uncertainty?: string
  material?: string
  count?: number
  deviation_unit?: string
}

export interface CapabilityProfile {
  id: string
  /** Standard parameter name. Raw registry variants are normalized away. */
  parameter: string
  role: ProfileRole
  unit: string
  /** `range` capabilities have min/max and buckets; `artifact` ones have `artifact`. */
  kind: 'range' | 'artifact'
  min: number | null
  max: number | null
  min_inclusive: boolean
  max_inclusive: boolean
  buckets: CapabilityBucket[]
  /** e.g. "Type K", "Pt-100", "24.12mm" - read with subtype_kind, not on its own. */
  subtype?: string
  subtype_kind?: SubtypeKind
  /**
   * Some certificates state an operating range narrower than the declared range
   * (e.g. a lux meter declared 0-199990 lux with an operating range of 60-5000).
   */
  operating_range?: { min: number; max: number; unit: string }
  /** Disambiguates profiles that share a parameter, e.g. "height" vs "outside". */
  mode?: string
  /** Present when kind === 'artifact'. */
  artifact?: ArtifactCapability
  /** Set when the profile came from a component of a composite asset. */
  component_id?: string
}

/**
 * A physical sub-instrument of a composite asset.
 *
 * Some components exist only because a certificate was found for them - the lab's
 * master list has no entry (e.g. asset 580 has certificates 580A/580B/580C but only
 * 580A is in the master list). Those have `has_master_record: false`, no serial and no
 * attributable calibration dates, so they must not be presented as fully tracked.
 */
export interface RegistryComponent {
  id: string
  instrument_desc: string | null
  make: string | null
  model: string | null
  serial_no: string | null
  asset_no: string | null
  certificate_file: string | null
  /** false when this component is known only from a certificate. */
  has_master_record: boolean
}

export interface RegistryAsset {
  /** Normalized asset number, e.g. "149". */
  id: string
  /** As printed, e.g. "149 HTAIPL/L". */
  asset_no: string
  asset_type: 'single' | 'composite'
  category: string | null
  instrument_desc: string | null
  make: string | null
  model: string | null
  serial_no: string | null
  usage: string | null
  calibrated_at: string | null
  report_no: string | null
  /** ISO date. */
  next_due_on: string | null
  calibration_status: string | null
  sop_references: string[]
  certificate_file: string | null
  /**
   * Every profile for this asset, including those from components of a composite,
   * so callers never have to walk two levels to filter.
   */
  capability_profiles: CapabilityProfile[]
  components?: RegistryComponent[]
}

export interface MasterInstrumentRegistry {
  schema_version: string
  generated_on: string
  source: {
    registry_schema_version: string | null
    normalization_map_version: string | null
  }
  asset_count: number
  profile_count: number
  assets: RegistryAsset[]
}

// ---------------------------------------------------------------------------------
// Narrowing helpers
// ---------------------------------------------------------------------------------

export function isSymmetric(a: Accuracy | null): a is SymmetricAccuracy {
  return a?.type === 'symmetric'
}

export function isFormula(a: Accuracy | null): a is FormulaAccuracy {
  return a?.type === 'formula'
}

export function isClassAccuracy(a: Accuracy | null): a is ClassAccuracy {
  return a?.type === 'class'
}

/**
 * True when an accuracy can be reduced to a number for a given reading.
 *
 * A class accuracy never can. A formula accuracy cannot when its basis is unresolved.
 * Callers that filter on accuracy should check this rather than assuming a value.
 */
export function isComparable(a: Accuracy | null): boolean {
  if (!a) return false
  if (a.type === 'symmetric') return true
  if (a.type === 'formula') return a.percent_of !== null || a.digits !== null
  return false
}
